export const ADD_TO_CART = 'ADD_TO_CART'
export const INCRE_TO_CART = 'INCRE_TO_CART'
export const DECRE_TO_CART = 'DECRE_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'